### ISSUE TITLE
Make config setup for target data/theme path

### ISSUE THREAD

**Issue by kination** [JaeYeopHan/myownresume#26]
Hello,
While I'm testing it, I found that fixed data/theme path and value is a bit inconvenient on working. I have to fix the setups in data.js every time after cleanup git status(it is not ignored by git), and need to add theme path in 'data/theme.js', 'src/theme/index.js' and some more files.

How do you think about...
- Setup data path as config file so make it easy to change target file
- Add theme loader to check all themes in 'src/theme' directory so user don't need to add every part of the code
- ...and would it be better to make data.js as JSON file? Cause it only includes data, there's no codes

Please look on, and share us if you have other plans for this.

Thanks.

**Comment by jbee37142** [comment]
Hello, @djKooks .
Thank you for your good feedback.
I did not care about this project on a personal schedule. Based on your feedback, we are planning an overall code refactoring. The project is still 0.0.2 version, so there are many deficiencies because it is for personal use. Please refer to the issue (https://github.com/JaeYeopHan/myownresume/issues/19) for the official release plan.

**Comment by kination** [comment]
@JaeYeopHan Okay, I got it. But I just want to know is how you think about it. 
So I mean, will it be okay to me to work on this? If you are planning to keep in current state, I'll let this as now. But if you think it will be better to fix as what I commented, I'll look on to update it. Because this will change some directory tree structure, I wanted to ask you to know how you think.

Thanks.

**Comment by jbee37142** [comment]
@djKooks Oh, I got it.
If the directory structure you want to change is better than it is now, I think it is right to proceed. However, it is difficult to grasp only the text registered in the current issue. If you register this content as a pull request in this repository, I will actively review it.

Thanks.

**Comment by kination** [comment]
@JaeYeopHan Okay, thanks!
I'll work on it when I have time. Please look on it and update if you think it looks better for working.
